# BASE DIRECTORYS
DIR_ASSETS = "assets/"
DIR_FONTS = DIR_ASSETS + "fonts/"
DIR_IMAGES = DIR_ASSETS + "images/"
DIR_SOUNDS = DIR_ASSETS + "sounds/"

# SIZES
SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1080

# TITLES
LAUNCHER_TITLE = "Launcher"
CHESS_TITLE = "Chess"
DAME_TITLE = "Dame"